// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoExpandTextareaController from "./auto_expand_textarea_controller"
application.register("auto-expand-textarea", AutoExpandTextareaController)

import AutosubmitselectController from "./autosubmitselect_controller"
application.register("autosubmitselect", AutosubmitselectController)

import ContactTypeController from "./contact_type_controller"
application.register("contact-type", ContactTypeController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import InssController from "./inss_controller"
application.register("inss", InssController)

import MaskController from "./mask_controller"
application.register("mask", MaskController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import UploadController from "./upload_controller"
application.register("upload", UploadController)
